[theme]
primaryColor = "#2E86C1"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E8F4FD"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false 